= Decentralized Arbitration and Mediation Network (DAMN)

_Research and Project Proposal by Third Key Solutions, LLC_

We have a global, borderless communication and transaction platform. We have global, borderless money. Why not a global, borderless justice system? An opt-in justice system. One that serves the community. Designed by the community, for the community. A robust system, that can address simple issues quickly and inexpensively, but can also address complex issues when needed. One that offers options, layers of choices, like who will decide (with options of one person or algorithm, pools of random jurors, pools of experts, collaboration of the parties, a mediation DAO, etc.), how long the decision-making process will take, and whether the dispute and the resolution will be made public or remain private.

Local court systems don’t offer these choices. More importantly, local courts cannot adequately deliver justice in a global, borderless, identity-optional system.

For decades, well-funded, sophisticated commercial parties have been using Alternative Dispute Resolution (ADR) methods to avoid lengthy, costly, cumbersome local court processes. By contract, parties can agree to waive their right to seek justice in a local court and have their disputes settled in a private forum, an alternative forum. One alternative forum, arbitration, is internationally recognized in more than 150 countries, thanks to the New York Convention (as it is commonly known) and its subsequent amendments <<1>>.

Why is that important? A local court order is often only enforceable within that local court’s jurisdiction. Perhaps the scope expands to the national border but rarely will a local court order be enforceable, without review, beyond its sovereign border. Enforcement beyond national borders is optional, meaning you can ask a local judge to enforce an order from another nation, but the court may say no. Contrast that with arbitration, where a private dispute decision can be enforceable using a local court in 150+ jurisdictions, pursuant to an international treaty. The treaty says the local court must enforce the private decision, it’s not optional. Additionally, it can protect parties from local lawsuits. If both parties have knowingly agreed to arbitration but one of them later tries to go to a local court instead, the local court will usually dismiss the case and direct the parties to arbitration. Therefore, arbitration allows parties to use local courts as an optional tool of enforcement while simultaneously protecting them from most local court processes.<<2>>

The question then is, can we design a private, decentralized, identity-optional, dispute resolution process, that can be delivered by a simple user interface, incorporated into both traditional and smart contracts, and be enforceable (at least in part) like traditional arbitration. We think the answer is yes and we’d like to try to build it.

== Why Mediation and Arbitration?

ADR isn’t new. In fact, mediation and arbitration systems have been used in cross-border disputes since 1800 B.C.E. <<2>>. Today, local courts and private parties use many different types of ADR <<3>>. But mediation and arbitration remain the two most broadly recognized and implemented systems of ADR and Online Dispute Resolution (ODR) <<4>>.

Mediation is a non-binding negotiation process that encourages parties to quickly resolve the dispute themselves, with assistance from a mediator or multiple mediators.<<5>> Arbitration is most often used as a binding dispute resolution process, where a third-party makes a decision that is enforceable in local courts.<<6>> Mediation is often used as a precursor to arbitration.

For any commercial transaction that spans more than one jurisdiction, an arbitration clause is a no-brainer. Every law student will suggest it, every expensive law partner will insist on it. Why? Because under the New York Convention, commercial arbitration decisions are enforceable and binding in 150+ countries around the world. A correctly designed and implemented smart-contract-based alternative-dispute-resolution process could produce decisions that are automatically recognized in 150+ jurisdictions, bypassing the local courts. With this framework, smart contracts become immediately applicable to a broad variety of commercial transactions, legally enforceable and universally recognized.

Reconciling the nuances of multiple jurisdictions is almost impossible. Arbitration cuts right through that and provides a predictable, uniform, playing-field across 150+ jurisdictions. If smart contracts are to be successful, they must be multi-jurisdictional and in order to be multi-jurisdictional they must include Alternative Dispute Resolution. But wait! Some futurists will say, “We don’t want to be multi-jurisdictional, we are non-jurisdictional!” The use of ADR doesn’t bind us to a single jurisdiction, it frees us from the quirks of any one jurisdiction. ADR allows us to design and implement our own neutral rules. We can use the current system to accelerate the dreams of futurists.

== Why Decentralized Funding?

Building a decentralized dispute resolution system is a challenging and ambitious endeavor. Building one that can deliver decisions that traditional legal systems will recognize and accept is even more ambitious. But we believe it can be done. If we succeed, decentralized dispute resolution will benefit all systems with decentralization as a core value. While this system may generate returns, direct profits are not the focus. It is ultimately an endeavor that promotes the politics of decentralization, the organizations daring to try alternative governance models, the entire ecosystem. By designing a system that makes justice inexpensive, efficient, transparent, and accessible, we reduce risk for all organizations that choose to implement it. The benefits of this project flow indirectly to all decentralized systems, by giving them access to a framework of decentralized justice. Therefore, a decentralized funding model is the best venue for such a project.

== Our Strategic Vision

With this project, we hope to decentralize and uncouple the functions of dispute resolution from national borders. We hope to offer solutions that provide real value to contract parties, making for more efficient, effective, accessible, inexpensive applications of justice in commerce.

* Design a suite of simple dispute resolution smart contracts that can be easily and quickly incorporated into other types of smart contracts
* Bridge smart contracts and traditional commercial/contract law relating to dispute resolution
* Bring the unique capabilities of smart contracts to the broader ADR community
* Expand the scope of ADR smart contracts to include and automate more and more of the mediation, arbitration, resolution and award functions
* Design decentralized, identity-optional decision-making options for dispute resolution

Note: Everything we are proposing is in the context of civil law (contracts and commercial transactions), not criminal law.

== Making Smart Contracts Accessible to Everyone

Smart contracts can resolve disputes between parties by applying rules and controlling funds on-chain, when all the rules, interactions, parties and funds are within the purview of the smart contract. Until that is the case, most commercial transactions cannot take advantage of smart contracts because too much of the interaction is outside the scope of the smart contract.

The DAMN project aims to bridge that gap by providing a tool that will allow traditional commercial contracts to incorporate a dispute resolution smart contract and the outcomes of smart contracts, in a broadly recognized and legally enforceable way. The goal is not to add unreadable and confusing legal gobbledygook to smart contracts, but to add smart contract automation to parts of traditional contracts. As time goes by, more and more of the traditional contract can be automated by the smart contract, making dispute resolution more efficient and accessible.

The goal of this project is to provide a transnational, multi-jurisdictional, uniform, legally enforceable dispute resolution framework for use within commercial contracts - whether they are traditional contracts, smart contracts, or more likely, hybrid contracts. First, we aim to bring commonly used ADR systems to smart contracts. By using proven systems as a base, we can quickly provide a usable framework for individuals, organizations, and even DAO to DAO resolutions. Second, we aim to expand the scope of smart contract ADR solutions to include rules designed specifically for smart contracts and technology based options that are otherwise impossible or impractical - such as crowdsourced juries or mediation DAO.

== Project Plan

This proposal is composed of multiple milestones. This funds requested here will fund only the first milestone. As each milestone is completed, it informs the direction of subsequent milestones and the funding needs. An incremental approach allows us to have manageable goals, focused deliverables, accountability to our funders and limited risk.

=== Technical Vision
_We begin this project with the following technical vision but we expect it to be highly modified based upon research conducted in Milestone 1._

Dispute Resolution Contract (DRC) is an independent smart contract used by two (or more) parties to govern any disputes that might arise during a contract or a transaction. For example, if Alice (the buyer) wants to buy a television from Bob (the seller) then Alice and Bob may choose to use a DRC to govern any disputes arising from the sale. In this case, Alice and Bob would be the two _parties_ engaging in the DRC. The DRC may hold funds in escrow or be part of multi-stage DRC contract. The DRC includes an interface, allowing either party to initiate a dispute claim and ADR mechanisms to resolve the dispute - such as formal arbitration, voting pool, or some other mechanism. DRCs will be funded by the contracting parties, e.g. Alice and Bob, and these funds could be used to pay for ADR services.

If no dispute is initiated during the term of the contract, both parties may consent to terminate the DRC. If the term ends and neither party has initiated a dispute, the DRC will terminate itself after a legally reasonable time.

Complex projects involving multiple milestones may choose to either use a single DRC per milestone or a more complex multi-stage DRC for the entire project. DRCs may be customized for specific types of contracts, such as a no-escrow service based DRC, product sale with escrow DRC, or by type of ADR such as a mediation with pool voting DRC, or a binding arbitration DRC. Most DRCs will use third parties to provide the ADR services.

Ultimately we envision DAMN running as a DAO offering a diverse range of DRC contracts, an interface for launching them, and a registry of entities providing ADR services. If the project is successful, we expect there will be multiple DAOs offering DRC services throughout the smart contract ecosystem.

=== Milestone 1 - Initial Legal and Systems Research

We propose a short-term research grant (3 months) to _evaluate existing alternative dispute resolution systems (mediation, arbitration, and possibly others) from the perspective of their use in smart contracts and DAOs_. The aim of this open source research project is to identify the most promising legal structures that can be used to bridge smart contracts and traditional commercial contracts.

==== Milestone 1 - Deliverable

The deliverable of this project is in two parts:

(1) a research report (document) outlining the most common ADR and ODR systems and evaluating their applicability for use in smart contracts and DAOs. The report will include analysis, recommendations, citations/bibliography, and next steps. This research report will be published under an open license (CC-BY-SA <<7>>).

(2) an accounting report of all funds used in this milestone

==== Milestone 1 - Timeframe
Approximately three months from funding to deliverable

==== Milestone 1 - Budget

Note: Most of the expenses of this project will be incurred in USD, the budget is therefore priced in USD. Funds awarded to this proposal will be converted as needed to ETH, BTC or USD for payment of expenses.

.Budget
[cols="n,>e,m”,options="footer"]
|==========================
| Legal Expert Consulting | $18,000
| Technical Expert Consulting | $6,000
| Training Expenses | $6,000
| *Total* | *$30,000*
|==========================

Legal Expert :: Funding to allow one or more legal experts to be focused on the delivery of this project. The funds will be used for salary and business-related expenses.

Technical Expert :: Funding to allow one or more technical experts to provide part-time advisory services to the legal expert. The funds will be used for salary and business-related expenses.

Training Expenses :: Short course trainings by accredited organizations, universities or widely recognized ADR institutions in the rules, frameworks and processes of ADR. Additional training will rapidly equip the lead Legal Expert with the necessary and current knowledge to evaluate different ADR frameworks. Training will also offer opportunities to engage with ADR subject-matter experts and engage those outside our community.

Note: The budget may be modified in order to adapt to changing circumstances or better allocate funds. It does not represent a commitment but rather a plan.


==== Milestone 1 - Funding Request

$30,000 USD.


==== Milestone 2 - Tentative Deliverable

A DRC prototype contract that allows third parties to offer basic mediation and/or escrow services to participants.

Note: We will be building software, not offering ADR services. We expect other providers to offer these services through this software.

==== Milestone 2 - Tentative Timeframe

To be determined during milestone 1 and subject of a new proposal

==== Milestone 2 - Tentative Funding Request

To be determined during phase 1 and subject of a new proposal: estimated $50,000 - $150,000 USD

==== Milestone 2 - Tentative Team

The budget for the second proposal will include funding for one more of each of the following Legal Expert, Technical Expert, Solidity Developer(s), UI/UX Designer(s) and Security Expert/Audit.

== Accountability and Transparency of Funding

Funds will be held according to the rules of the funding platform. Ideally, the funds will be held in a multi-signature address in BTC or ETH and distributed according to a schedule. We will provide a public accounting report for all funds consumed in Milestone 1. The funding contract signatories will be Pamela Morgan and Andreas M. Antonopoulos. Funds will be converted to ETH, BTC and USD as necessary to execute on the deliverables.

== Licensing

All deliverables from this project will be licensed under open source licenses. Documentation and media will be licensed under Creative Commons Attribution Share-Alike (CC-BY-SA <<7>>). Software will be licensed Lesser GNU Public License (LGPL) v3 <<8>> (same as theDAO code).

== Future Plans

The fulfillment of the strategic vision outlined in this proposal will allow:

* Modular development of discrete smart contracts that provide specific ADR services to individuals, organizations, and communities, by way of agreement in traditional or smart contracts.
* Mediation and/or Arbitration via voting pools, community justice, or special purpose DAO
* Mediation and/or Arbitration via domain experts (real estate, art, commerce, manufacturing)
* Mediation and/or Arbitration with “mock jury” drawn randomly from a pool
* Online arbitration that produces binding awards
* Automated escrow, surety bonds, fidelity bonds and other risk mitigation systems
* Public or private resolution of disputes
* Template contract clauses to be included in traditional commercial contracts; Opt-in agreement to be included in smart commercial contracts
* Contract generators for the most common commercial transactions (service, product etc)


== Team

This proposal is submitted and will be managed by Third Key Solutions LLC (https://www.thirdkey.solutions/), under the management of Pamela Morgan (CEO).

Third Key Solutions designs solutions for corporate governance and individual security. We are focused on applying multi-signature and smart-contract technology to solve real-life problems, in bitcoin, ethereum and across the crypto-currency space. Third Key Solutions has repeatedly received requests for mediation, arbitration, and escrow. Lacking a decentralized and open platform to deliver these services, we have so far declined to engage. We need a DAMN solution! With expertise spanning both technology and law, Third Key Solutions is perfectly positioned to implement this proposal. Our desire to solve this problem is motivated in the best tradition of open-source: “scratch your own itch” <<9>>.

Pamela Morgan :: Pamela is an entrepreneur, attorney and educator with degrees in Small Business Management, Business Administration with a concentration in Computer Programming, and Law. She began focusing her law practice on bitcoin and cryptocurrencies in early 2014. She is a widely respected authority on multi-signature governance and legal innovation with cryptocurrencies. She has been publicly advocating for the use of smart contracts and ADR, combined, since 2014. To date, she has completed three International Commercial Arbitration continuing legal education courses and one Mediation course. Pamela will be the lead Legal Expert in this proposal.

Andreas M. Antonopoulos :: Andreas is a technologist and entrepreneur who has become one of the most well-known and well-respected figures in bitcoin and the broader crypto-currency space. Andreas is the author of “Mastering Bitcoin”, widely considered the best technical guide to bitcoin. With more than 20 years experience in security and distributed systems, he is responsible for technology strategy, security operations and security consulting at Third Key Solutions. Andreas will be the lead Technical Expert in this proposal.

During Milestone 1 we hope to identify additional team members to work with us to implement the strategic vision. These include additional Legal and ADR Experts, additional Technical Experts, Solidity Developer(s), UI/UX Designer(s) and Security Expert(s)/Audit.

== Collaboration

This project will invite public participation and voluntary collaboration. Project activity will occur on public forums and open platforms, such as Github, reddit, etc.


== Further Reading
[[[1]]] Wikipedia, “Convention on the Recognition and Enforcement of Foreign Arbitral Awards” https://en.wikipedia.org/wiki/Convention_on_the_Recognition_and_Enforcement_of_Foreign_Arbitral_Awards

[[[2]]] These are broad statements and readers should be aware that once a local court is involved they may find reasons to circumvent the arbitration contract if, for example, the parties didn't know they were agreeing to arbitration. Additionally, if the arbitration is not conducted properly, according to the requirements of international arbitration law, the award can be disregarded and the parties may be subject to that or another court's jurisdiction.

[[[2]]] Wikipedia, “Alternative Dispute Resolution”
https://en.wikipedia.org/wiki/Alternative_dispute_resolution

[[[3]]] J. Barret, Association of Conflict Resolution, "A History of Alternative Dispute Resolution" http://www.adr.gov/events/2009/may7-2009-materials-history.pdf

[[[4]]] Legal Information Institute, Cornell University, “Alternative Dispute Resolution” https://www.law.cornell.edu/wex/alternative_dispute_resolution

[[[5]]] Legal Information Institute, Cornell University, “Mediation”
https://www.law.cornell.edu/wex/mediation

[[[6]]] Legal Information Institute, Cornell University, “Arbitration”
https://www.law.cornell.edu/wex/arbitration

[[[7]]] Creative Commons Attribution-ShareAlike 4.0 International License http://creativecommons.org/licenses/by-sa/4.0/

[[[8]]] GNU Lesser General Public License v3.0 http://choosealicense.com/licenses/lgpl-3.0/

[[[9]]] Scratch Your Own Itch, From “The Cathedral and the Bazaar” http://www.catb.org/esr/writings/homesteading/cathedral-bazaar/ar01s02.html
